Resources:
  KeyPair:
    Type: AWS::EC2::KeyPair
    Properties:
      KeyName: term-assignment
  MyInstance:
    Type: "AWS::EC2::Instance"
    Properties:
      InstanceType: "t3.micro"
      ImageId: "ami-0557a15b87f6559cf"
      KeyName: !Ref KeyPair
      SecurityGroupIds:
        - !Ref SecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          sudo apt update
          sudo apt-get install nginx -y 
          sudo apt-get install curl
          curl -fsSL https://deb.nodesource.com/setup_14.x | sudo -E bash - 
          sudo apt-get install -y nodejs
          cd /var/www/html/
          git clone https://github.com/UmatiyaFaiza/CloudProject.git
          sudo rm index.nginx-debian.html      
          cd CloudProject
          sudo npm install
          sudo npm run build
          sudo cp -r build /var/www/html
          cd ../
          sudo mv build/* .
  SecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "Security rule"
      SecurityGroupIngress:
        - IpProtocol: "-1"
          FromPort: 0
          ToPort: 65535
          CidrIp: "0.0.0.0/0"
        - IpProtocol: "-1"
          FromPort: 0
          ToPort: 65535
          CidrIpv6: "::/0"